### ISSUE TITLE
Non-static method requires a target (default field printer impl)

### ISSUE THREAD

**Issue by haf** [eiriktsarpalis/TypeShape#19]
### Description

When using the field printer abstraction on an Exception:

    dotnet run --framework netcoreapp2.0 --project src/Logary.Tests/Logary.Tests.fsproj -- --summary --debug --filter "logary/Formatting/json/encoding/nested/Exception" --sequenced

this stack trace is generated:

```
  System.Reflection.TargetException: Non-static method requires a target.
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Logary.Internals.TypeShape.Core.Core.ShapeMember`2.Project(DeclaringType instance) in /logary/paket-files/eiriktsarpalis/TypeShape/src/TypeShape/TypeShape.fs:line 1169
   at Logary.Formatting.JsonHelper.mkFieldPrinter@115-3.Invoke(DeclaringType x) in /logary/src/Logary/Formatting/JsonHelper.fs:line 115
   at Logary.Formatting.JsonHelper.toJsonAux@319-47.Invoke(JsonObject s, Lazy`1 x) in /logary/src/Logary/Formatting/JsonHelper.fs:line 321
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source)
   at Logary.Formatting.JsonHelper.toJsonAux@317-46.Invoke(T input) in /logary/src/Logary/Formatting/JsonHelper.fs:line 318
   at Logary.Formatting.JsonHelper.toJsonAux@319-47.Invoke(JsonObject s, Lazy`1 x) in /logary/src/Logary/Formatting/JsonHelper.fs:line 321
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source)
   at Logary.Formatting.JsonHelper.toJsonAux@317-46.Invoke(T input) in /logary/src/Logary/Formatting/JsonHelper.fs:line 318
   at Logary.Tests.Formatting.jsonTests@235-118.Invoke(Exception e) in /logary/src/Logary.Tests/Formatting.fs:line 236
   at FsCheck.Testable.evaluate[a,b](FSharpFunc`2 body, a a)
Focus on failure:
	ftestPropertyWithConfig (1651171337, 296430393) "Exception" <Expecto>
```

when projecting `InnerException`,

for this commit https://github.com/logary/logary/commit/c4e4c6f2bf2a1c5a75d27375d8c8ef3fdbce1f12

Repro by cloning, then `./build.sh` then the command line above.

### Actual behavior

Crash

### Notes

Trace looks like:

```
toJson System.Exception
toJsonCached System.Exception
toJsonAux System.Exception
toJsonCached System.String
toJsonAux System.String
Projecting field System.String Message
Project path [|"Message"|]
Get Message for System.Exception: l1
   at Logary.Tests.Program.failer@85T.Invoke(String message) in /logary/src/Logary.Tests/Program.fs:line 86
   at Logary.Tests.Program.generator@101-3.Invoke(Boolean _arg10) in /logary/src/Logary.Tests/Program.fs:line 102
toJsonCached System.Collections.IDictionary
toJsonAux System.Collections.IDictionary
Projecting field System.Collections.IDictionary Data
Project path [|"Data"|]
Get Data for System.Exception: l1
   at Logary.Tests.Program.failer@85T.Invoke(String message) in /logary/src/Logary.Tests/Program.fs:line 86
   at Logary.Tests.Program.generator@101-3.Invoke(Boolean _arg10) in /logary/src/Logary.Tests/Program.fs:line 102
toJsonCached System.Exception
Projecting field System.Exception InnerException
Project path [|"InnerException"|]
Get InnerException for System.Exception: l1
   at Logary.Tests.Program.failer@85T.Invoke(String message) in /logary/src/Logary.Tests/Program.fs:line 86
   at Logary.Tests.Program.generator@101-3.Invoke(Boolean _arg10) in /logary/src/Logary.Tests/Program.fs:line 102
Project path [|"Message"|]
Get Message for <null>
```

So it would seem that the InnerException, while of type `Exception`, is projected despite being null, because it type is cached.

### Workaround

```
    let mkFieldPrinter (field: IShapeMember<'DeclaringType>) =
      field.Accept {
        new IMemberVisitor<'DeclaringType, string * ('DeclaringType -> Json)> with
          member __.Visit(field: ShapeMember<'DeclaringType, 'Field>) =
            let fp = toJsonCached<'Field> ctx
            let project declaringValue =
              match box declaringValue with
              | null -> Json.Null
              | _ -> field.Project declaringValue |> fp
            field.Label, project
      }
````

**Comment by eiriktsarpalis** [comment]
I assume you are formatting exceptions using [this branch](https://github.com/logary/logary/blob/a3fdbc945454cfb1b27a12d02e1fafe4fdc69f21/src/Logary/Formatting/JsonHelper.fs#L212-L237)? If so, it doesn't seem like it's using any lenses to access fields. Perhaps `Shape.(Exception|_|)` isn't working as expected and it is being handled by the POCO shape?

**Comment by haf** [comment]
No, here: https://github.com/logary/logary/commit/c4e4c6f2bf2a1c5a75d27375d8c8ef3fdbce1f12#diff-1988da8fedf7e99454f3e0c4eb272bc9

Yes, that commit uses the POCO matcher; I hadn't added the exception matcher by then. But it's a general issue that properties on null are being called/gotten.

**Comment by eiriktsarpalis** [comment]
So you're saying that the projector is failing because the target is null? If that's the case, not sure the library itself can do much about it (just like evaluating the property of a null object). You could however add provision for external null checking like the following one https://github.com/eiriktsarpalis/TypeShape/blob/198473bb2e74e68823fe457f511af48fe04ce17b/src/TypeShape/Applications/Combinators.fs#L30
