### ISSUE TITLE
empty<RecursiveType> with optional recursive field

### ISSUE THREAD

**Issue by chillitom** [eiriktsarpalis/TypeShape#51]
```fsharp
#r "nuget: TypeShape"
type RecursiveType= {
    Child: RecursiveType option
}
empty<RecursiveType>;;
```
gives 
```
System.Exception: Type 'FSI_0006+RecursiveType' does not support empty values.
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1439.Invoke(String message) in D:\a\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1439
   at TypeShape.Empty.mkEmptyFuncAux@62-8.TypeShape.Core.Core.ITypeVisitor<TypeShape.Empty.EmptyFunc<'T>>.Visit[t]() in /app/src/TypeShape/Applications/Empty.fs:line 64
   at TypeShape.Empty.mkEmptyFuncCached[T](TypeGenerationContext ctx) in /app/src/TypeShape/Applications/Empty.fs:line 20
   at TypeShape.Empty.mkMemberInitializer@31-2.TypeShape.Core.Core.IMemberVisitor<'DeclaringType, TypeShape.Empty.EmptyFieldInitializer<'DeclaringType>>.Visit[a](ShapeMember`2 shape) in /app/src/TypeShape/Applications/Empty.fs:line 33
   at TypeShape.Empty.mkEmptyFuncAux$cont@37[T](TypeGenerationContext ctx, FSharpTypeFunc mkMemberInitializer, TypeShape`1 matchValue, Unit unitVar) in /app/src/TypeShape/Applications/Empty.fs:line 0
   at TypeShape.Empty.mkEmptyFuncAux[T](TypeGenerationContext ctx) in /app/src/TypeShape/Applications/Empty.fs:line 118
   at TypeShape.Empty.mkEmptyFuncCached[T](TypeGenerationContext ctx) in /app/src/TypeShape/Applications/Empty.fs:line 20
   at TypeShape.Empty.mkEmptyFunc[T]() in /app/src/TypeShape/Applications/Empty.fs:line 17
   at TypeShape.Empty.empty[T]() in /app/src/TypeShape/Applications/Empty.fs:line 153
   at <StartupCode$FSI_0007>.$FSI_0007.main@()
Stopped due to error
```

Given that the child type is optional shouldn't it be possible for TypeShape to construct an empty `RecursiveType` e.g. `{Child: None}`?

**Comment by eiriktsarpalis** [comment]
That restriction is forced by the sibling function [`notEmpty<T>`]( https://github.com/eiriktsarpalis/TypeShape/blob/main/src/TypeShape/Applications/Empty.fs#L157), which populates variable-length collections (`'T option`, `'T list`, `'T[]`) with a single empty element. I posted #52 which relaxes the restriction by delaying cycle detection to the runtime phase.
